run:
  concurrency: 4
  timeout: 5m
  tests: true
  modules-download-mode: vendor
issues:
  exclude-dirs:
    - vendor
    - test/utils/k8simported
    - pkg/version
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
    - path: "test/e2e/serial/*"
      linters:
        - dupl
        - lll
    - path: "test/utils/*"
      linters:
        - dupl
        - lll
linters:
  disable-all: true
  enable:
#    - errcheck
    - bodyclose
#    - copyloopvar
    - depguard
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
linters-settings:
  revive:
    rules:
      - name: comment-spacings
  misspell:
    locale: US
    ignore-words:
      - NRO
      - nro
      - numaresource
      - numa
      - NUMA
  depguard:
    rules:
      main:
        list-mode: original
        files:
          - $all
          - "!$test"
        deny:
          - pkg: "k8s.io/kubernetes"
            desc: Importing k8s.io/kubernetes as library is not supported
      test:
        list-mode: lax
        files:
          - $test
        deny:
          - pkg: "k8s.io/kubernetes"
            desc: Importing k8s.io/kubernetes as library is not supported
