FROM docker.io/golang:1.25 AS builder

WORKDIR /go/src/github.com/openshift-kni/numaresources-operator
COPY . .

RUN make build-numazone

FROM registry.access.redhat.com/ubi9/ubi-minimal
COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/numazone /bin/numazone
ENTRYPOINT ["/bin/numazone", "-alsologtostderr", "-v", "3"]
