FROM docker.io/golang:1.19 AS builder

WORKDIR /go/src/github.com/openshift-kni/numaresources-operator
COPY . .

RUN make build-e2e-all
RUN make build-numacell

FROM registry.access.redhat.com/ubi9/ubi-minimal
COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/e2e-nrop*.test /usr/local/bin
COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/run-e2e-nrop-serial.sh /usr/local/bin
COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/numacell /bin
COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/pause /
ENTRYPOINT ["/usr/local/bin/run-e2e-nrop-serial.sh"]
