FROM registry.access.redhat.com/ubi9/ubi-minimal
COPY e2e-nrop-*.test /usr/local/bin/
COPY run-e2e-nrop-*.sh /usr/local/bin
COPY numacell /bin
COPY pause /
COPY topics.json /usr/local/share
WORKDIR /usr/local/bin
CMD ["./run-e2e-nrop-serial.sh"]
