FROM docker.io/golang:1.22 AS builder

WORKDIR /go/src/github.com/openshift-kni/numaresources-operator
COPY . .

RUN make build-pause

FROM registry.access.redhat.com/ubi9/ubi-minimal
COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/pause /
ENTRYPOINT ["/pause"]
