FROM registry.access.redhat.com/ubi8/ubi-minimal
COPY manager /bin/numaresources-operator
# bundle the operand, and use a backward compatible name for RTE
COPY exporter /bin/resource-topology-exporter
RUN mkdir /etc/resource-topology-exporter/ && \
    touch /etc/resource-topology-exporter/config.yaml
RUN microdnf install pciutils
USER 65532:65532
ENTRYPOINT ["/bin/numaresources-operator"]
