FROM docker.io/golang:1.24 AS builder

WORKDIR /go/src/github.com/openshift-kni/numaresources-operator
COPY . .

RUN make bin/pfpsyncchk

FROM quay.io/openshift/origin-cli:4.21

RUN yum install -y jq procps-ng tar rsync

COPY --from=builder /go/src/github.com/openshift-kni/numaresources-operator/bin/pfpsyncchk /usr/bin/pfpsyncchk

COPY must-gather/collection-scripts/* /usr/bin/

ENTRYPOINT ["/usr/bin/gather"]
