FROM registry.access.redhat.com/ubi8/ubi-minimal
COPY e2e-nrop-*.test /usr/local/bin/
COPY run-e2e-nrop-serial.sh /usr/local/bin
COPY numacell /bin
COPY pause /
ENTRYPOINT ["/usr/local/bin/run-e2e-nrop-serial.sh"]
