apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: numaresources-controller-manager
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    scheme: https
    targetPort: 8443
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      insecureSkipVerify: false
      serverName: numaresources-controller-manager-metrics-service.numaresources.svc
  selector:
    matchLabels:
      control-plane: controller-manager
