apiVersion: v1
kind: Pod
metadata:
  generateName: chk-pod-
spec:
  schedulerName: topo-aware-scheduler
  containers:
  - name: ctrreschk
    image: quay.io/fromani/ctrreschk:v0.0.11
    imagePullPolicy: Always
    command: ["/ctrreschk", "-w", "align"]
    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 1
        memory: 256Mi
