
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tlsConfig:
        caFile: /etc/tls/client/client-ca-file
        certFile: /etc/tls/private/tls.crt
        insecureSkipVerify: false
        keyFile: /etc/tls/private/tls.key
  selector:
    matchLabels:
      control-plane: controller-manager
