# permissions for end users to edit numaresourcesschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: numaresourcesscheduler-editor-role
rules:
- apiGroups:
  - nodetopology.openshift.io
  resources:
  - numaresourcesschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodetopology.openshift.io
  resources:
  - numaresourcesschedulers/status
  verbs:
  - get
