# permissions for end users to view numaresourcesschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: numaresourcesscheduler-viewer-role
rules:
- apiGroups:
  - nodetopology.openshift.io
  resources:
  - numaresourcesschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodetopology.openshift.io
  resources:
  - numaresourcesschedulers/status
  verbs:
  - get
