apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/numaresources-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: numaresources-must-gather-4-20
    appstudio.openshift.io/component: numaresources-must-gather-4-20
    pipelines.appstudio.openshift.io/type: build
  name: numaresources-must-gather-4-20-on-push
  namespace: telco-5g-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/telco-5g-tenant/numaresources-must-gather-4-20:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: .konflux/must-gather/must-gather.konflux.Dockerfile
  - name: build-source-image
    value: "true"
  pipelineRef:
    name: build-pipeline-must-gather
  taskRunTemplate:
    serviceAccountName: build-pipeline-numaresources-must-gather-4-20
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}