#!/bin/bash

# generate /must-gather/version file
. version
echo "performance-addon-operator/must-gather" > /must-gather/version
version >> /must-gather/version

# machine/node resources
resources+=(nodes machineconfigs machineconfigpools featuregates kubeletconfigs crd)

# run the collection of resources using must-gather
for resource in ${resources[@]}; do
  /usr/bin/oc adm inspect --dest-dir must-gather --all-namespaces ${resource}
done

# Collect NRO details
/usr/bin/gather_nro

exit 0
