name: CI Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  golint:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
        args: --timeout=15m0s --verbose
